apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-nginx
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.27.2-alpine
        name: nginx
        ports:
        - containerPort: 80
